name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:

jobs:
  cifuzz_job:
    name: CIFuzz Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 16  # Update to Node.js 16 or a more recent version

      - name: Set execute permissions for scripts
        run: |
          chmod +x name.sh build.sh run.sh

      - name: Build CIFuzz Docker Image
        run: |
          ./build.sh

      - name: Run CIFuzz Docker Container
        run: |
          ./run.sh
